# Generated by Django 4.0 on 2021-12-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_avatar_customuser_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
