# Generated by Django 4.0 on 2021-12-12 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=280)),
                ('image', models.ImageField(blank=True, upload_to='tweet_photos/%Y/%m/%d/')),
                ('published', models.DateTimeField(default='created')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='accounts.customuser')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='tweets_liked', to=settings.AUTH_USER_MODEL)),
                ('quote_tweeted_by', models.ManyToManyField(blank=True, related_name='tweets_quote_retweeted', to=settings.AUTH_USER_MODEL)),
                ('retweeted_by', models.ManyToManyField(blank=True, related_name='tweets_retweeted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
