# Generated by Django 4.0 on 2021-12-15 19:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_alter_follow_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=280)),
                ('image', models.ImageField(blank=True, upload_to='tweet_photos/%Y/%m/%d/')),
                ('published', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='accounts.customuser')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='tweets_liked', to=settings.AUTH_USER_MODEL)),
                ('quote_tweeted_by', models.ManyToManyField(blank=True, related_name='tweets_quote_retweeted', to=settings.AUTH_USER_MODEL)),
                ('retweeted_by', models.ManyToManyField(blank=True, related_name='tweets_retweeted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
