# Generated by Django 4.0 on 2021-12-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='published',
            field=models.DateTimeField(),
        ),
    ]
