# Generated by Django 4.0 on 2021-12-12 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_alter_tweet_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='created',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
