# Generated by Django 4.0 on 2021-12-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_remove_tweet_created_alter_tweet_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-published']},
        ),
    ]
